[project]
name = "ticket-automation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ddddocr>=1.5.6",
    "playwright>=1.56.0",
    "python-dotenv>=1.2.1",
]
